name: Voyager CraftWorld Daily Bot

on:
  schedule:
    # Menjalankan setiap hari pada pukul 00:00 UTC (07:00 pagi WIB)
    - cron: '0 0 * * *'

  workflow_dispatch: # Memungkinkan menjalankan manual

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode repository
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Pastikan versi Node.js ini kompatibel dengan skripmu

      - name: Install Node.js dependencies
        run: npm ci

      - name: Jalankan Voyager Bot dengan Environment Variables dari Secrets
        env:
          PRIVATE_KEYS: ${{ secrets.PRIVATE_KEYS }}
          RPC_URL: ${{ secrets.RPC_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

          # Optional secrets, skrip akan mencoba membacanya jika ada
          VOYAGER_API_KEY: ${{ secrets.VOYAGER_API_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

          # --- BARIS PROXIES_DATA, PROXY_USER, PROXY_PASS DIHAPUS DARI SINI ---

        run: node index.js
